### ISSUE TITLE
Support Ping and Restart ICE API Endpoints for Webrtc Client

### ISSUE THREAD

**Issue by luongngocminh** [8xFF/atm0s-media-server#119]

**Comment by giangndm** [comment]
@luongngocminh can you update more details info? many be SDK is using Ping so we should now how client implement for correcting implemented in server. Now we see two parts need to implement:

- gateway
- media-server it-self (only webrtc because js-sdk only use webrtc)

**Comment by giangndm** [comment]
ref https://github.com/8xFF/atm0s-media-server/issues/7

**Comment by giangndm** [comment]
cleanup for new version
