### ISSUE TITLE
feat: connector sending event to external consumer over NATS or Kafka

### ISSUE THREAD

**Issue by giangndm** [8xFF/atm0s-media-server#121]
https://github.com/8xFF/atm0s-media-server/pull/120 PR only implemented core flow, for external using we need to implement external message queue producer

**Comment by Yosef0987** [comment]
NATS will be a good option

**Comment by giangndm** [comment]
@Yosef0987 yeah, I think so. NATS is easier than Kafka to start.

May be we can use protobuf instead of json for event serialize, which have better performance and bandwith save, an also easy to integrate will all other language like NodeJs or Golang

**Comment by luongngocminh** [comment]
@giangndm protobuf seems to be having a much higher overhead than JSON, for both safe typing and implementation, it's good to have, but I think JSON is enough for now?

**Comment by giangndm** [comment]
@luongngocminh, I believe you're mistaken. Protobuf is a binary codec, making it faster and more efficient than JSON. You can find several benchmark tests online that show Protobuf's superior performance.

https://nilsmagnus.github.io/post/proto-json-sizes/
and https://www.codingexplorations.com/blog/performance-comparison-protobuf-marshaling-vs-json-marshaling-in-go

**Comment by luongngocminh** [comment]
I know the benefits of using protobuf, but my point is that the implementation to convert the internal rust event enum to protobuf will have more boilercode, is it really matter that much or we can just provide it as an option later.

**Comment by giangndm** [comment]
Ok, let do it in simplest way

**Comment by luongngocminh** [comment]
@giangndm the connector pr is up
