### ISSUE TITLE
Docker not working due to missing dependency

### ISSUE THREAD

**Issue by luongngocminh** [8xFF/atm0s-media-server#145]
Running the script
`docker run --net=host ghcr.io/8xff/atm0s-media-server:master ` 
would resulted in an error: 
`/atm0s-media-server: error while loading shared libraries: libsoxr.so.0: cannot open shared object file: No such file or directory`

**Comment by giangndm** [comment]
It seam to missing features in libsoxr crate.

https://github.com/giangndm/libsoxr-sys/blob/fix-build-crossplatform-macos/build.rs
