### ISSUE TITLE
Does Support Real-Time DRM Encryption?

### ISSUE THREAD

**Issue by binhduong85** [8xFF/atm0s-media-server#170]
Could someone confirm whether this feature is currently supported, and if not, are there plans to implement it in the future?

Thank you for your attention to this matter. I look forward to hearing from you soon.

**Comment by giangndm** [comment]
@binhduong85 We are focusing on releasing the main features, so DRM will be considered in the future. If you have any suggestions on how to integrate DRM, feel free to send a PR or discuss it here.
