### ISSUE TITLE
Inconsistency in term naming for "token", "secret" and "key"

### ISSUE THREAD

**Issue by luongngocminh** [8xFF/atm0s-media-server#171]
For example, the root "token", for generating other JWT Tokens, should be called "secret" or "keys". This appeared in multiple `servers/` code.

```rust
    // in servers/media-server/src/server.rs

    /// Current Token
    #[arg(env, long, default_value = "insecure")]
    token: String,
```
While in the implementations of `packages/cluster/`, the root "token" is correctly termed "key", or "static_key" to be exact.
And in "token"_generator server, the check for token is confusing at best:
```rust
// servers/media-server/src/server/token_generate/http.rs
if !app_secret.0.eq(&data.1.token) {
            return Ok(Json(Response {
                success: false,
                error: Some("INVALID_TOKEN".to_string()),
                data: None,
            }));
        }
```

We should strictly normalize all the terms to avoid such confusion.

**Comment by giangndm** [comment]
@luongngocminh can you draft a suggestion?

**Comment by luongngocminh** [comment]
@giangndm https://github.com/8xFF/atm0s-media-server/pull/174 here you go

**Comment by luongngocminh** [comment]
#174 Merged
