### ISSUE TITLE
Whip/Whep Client failure because of Content-Type: application/trickle-ice-sdpfrap

### ISSUE THREAD

**Issue by moksh-samespace** [8xFF/atm0s-media-server#176]
Whip and Whep client fails to connect with error `415 Unsupported Media Type`.

**Comment by giangndm** [comment]
@moksh-samespace thank for reporting issue. I will check it and made a PR

**Comment by giangndm** [comment]
@moksh-samespace I just merge a PR for fixing this issue, can you re-check with master branch?

**Comment by giangndm** [comment]
Fixed in https://github.com/8xFF/atm0s-media-server/pull/179
