### ISSUE TITLE
Inner/Local Gateway: pinging global gateway should be optional

### ISSUE THREAD

**Issue by luongngocminh** [8xFF/atm0s-media-server#192]
<img width="996" alt="image" src="https://github.com/8xFF/atm0s-media-server/assets/9526028/aef6bf0e-9d36-4544-a6cb-02bb2eae4ac2">
Pinging global gateway should be optional, or at least some way to suppress the error message

**Comment by giangndm** [comment]
We will refactor gateway to work as both inner and global, then this issue will be resolved
