### ISSUE TITLE
Deploy multi zones cluster

### ISSUE THREAD

**Issue by giangndm** [8xFF/atm0s-media-server#205]
We need a simple and cost effective way to deploy multi zones cluster for demo cluster. We have some possible way:

- docker compose
- use binary directly

In my opinion docker compose is better, we should create a docker compose repo which has:

- local cluster with all nodes
- separated docker compose for each server

**Comment by luongngocminh** [comment]
@giangndm for autoupdates we can just package https://github.com/containrrr/watchtower included in the docker compose file, and host the docker compose yaml along with a bash script in a repo so we can use a single command like `(wget -O "script_url") > /bin/bash` to deploy it anywhere.
Custom configurations can be config through a .env file or be set using the -e flag

**Comment by giangndm** [comment]
@luongngocminh I think we will have 2 version:

- simple version use docker-compose direct and above watchtower
- advance version can be a deployer service which run independent for deploying autoscale multi-zones cluster

**Comment by luongngocminh** [comment]
How often do you think we will need to update the docker-compose file? Unless there are breaking changes, I don't think it's that much of an issue to be needed to be done automatically.
We can provide an update script also if that's necessary.

**Comment by giangndm** [comment]
@luongngocminh Sure, maybe the config will be changed during alpha version, but we can manual update that or simply use cronjob

**Comment by luongngocminh** [comment]
Now we can easily deploy a cluster or single server using this: https://github.com/8xFF/atm0s-docker-compose
