### ISSUE TITLE
RFCs write up

### ISSUE THREAD

**Issue by luongngocminh** [8xFF/atm0s-media-server#208]

**Comment by giangndm** [comment]
The most important RFCs is landing in https://github.com/8xFF/RFCs

- [x] [RFC-0003](https://github.com/8xFF/rfcs/pull/3) cluster structure 
- [x] [RFC-0005](https://github.com/8xFF/rfcs/pull/5) WebRTC SDK protocol https://github.com/8xFF/rfcs/pull/5

**Comment by giangndm** [comment]
cleanup for new version
