### ISSUE TITLE
feat: connector send event hooks to external

### ISSUE THREAD

**Issue by giangndm** [8xFF/atm0s-media-server#341]
For easier integrating with other system, connector should have hooks mechanism. Ideally protocol is:

- Direct HTTP
- Message Queue like NATS

The message should be sent with JSON schema for better integration without external dependencies

**Comment by marverlous811** [comment]
@giangndm I have some questions
- which events should we send via the hooks?
- Does the hook have a scope, or can it consume events from all sessions, nodes, and peers...? 
- Should we allow any third-party system to register the hooks, and what factors differentiate between the hook of each third-party system?

**Comment by giangndm** [comment]
I think it is global config then it will send event of all rooms and peers

**Comment by jibon57** [comment]
@giangndm I think tracks related events also important to have. Like track added, updated, subscribed, unsubscribed, muted/unmuted etc.

**Comment by giangndm** [comment]
@jibon57 I see. I also important too.

@marverlous811 So we can consider with: room, peer, track events
