### ISSUE TITLE
feat: room metadata

### ISSUE THREAD

**Issue by jibon57** [8xFF/atm0s-media-server#377]
# Issue Template

## Description

During developing a web conferencing solution we often need to store few room related information so that we can use those in various scenario. At present we can set metadata during join and with tracks. Having a dedicated API/option to set room metadata will be helpful, may be during generate join token. Also should have API method to update those metadata & client should receive events based on update. Without having this option will be hard during development. 

## Steps to Reproduce

1. Step 1
2. Step 2
3. Step 3

## Expected Behavior

Please describe what you expected to happen.

## Actual Behavior

Please describe what actually happened.

## Screenshots

If applicable, add screenshots to help explain the issue.

## Environment

- Operating System:
- Browser (if applicable):
- Version (if applicable):

## Additional Information

Related discussion: https://github.com/8xFF/atm0s-media-server/discussions/358

**Comment by giangndm** [comment]
This resolved with https://github.com/8xFF/atm0s-media-server/pull/386
